config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {registrions: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  resources :guardians do
    resources :kids
    resources :cases do
      resources :daily_reports
    end
  end

    # root "controller#view"
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  root "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :guardian
  belongs_to :kid
  belongs_to :therapist, optional: true
  belongs_to :teacher, optional: true
  has_many :daily_reports
  has_many :goals
  has_many :surveys
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :guardian, optional: true
  belongs_to :therapist, optional: true
  belongs_to :teacher, optional: true
  belongs_to :case
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :case
end

app/models/guardian.rb
class Guardian < User
  has_many :kids
  has_many :cases
  has_many :daily_reports
end

app/models/kid.rb
class Kid < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :birthdate
  validates_presence_of :has_diagnosis
  validates_presence_of :guardian_id

  belongs_to :guardian
  has_one :case
  has_many :therapists, :through => :case
  has_many :teachers, :through => :case
  has_many :goals, :through => :case
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :case
  has_many :questions
end

app/models/teacher.rb
class Teacher < User
  has_many :cases
  has_many :daily_reports
  has_many :kids, :through => :cases
end

app/models/therapist.rb
class Therapist < User
  has_many :cases
  has_many :kids, :through => :cases
  has_many :goals, :through => :cases
  has_many :daily_reports
end

app/models/user.rb
class User < ApplicationRecord
  has_many :daily_reports
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_uniqueness_of :email, message: 'Email Has Already Being Used'
  validates_presence_of :role
  enum role: [:guardian, :therapist, :teacher]

  def full_name
    self.first_name + " " + self.last_name
  end

  def is_guardian?
    self.role == "guardian"
  end

  def is_therapist?
    self.role == "therapist"
  end

  def is_teacher?
    self.role == "teacher"
  end

  def has_kids?
    self.kids
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @guardian = Guardian.find(params[:guardian_id])
    @cases = @guardian.cases.all
  end

  def new
    @guardian = Guardian.find(params[:guardian_id])
    @case = @guardian.cases.new
  end

  def create
    @guardian = Guardian.find(params[:guardian_id])
    @case = @guardian.cases.new(case_params)

    if @case.save
      redirect_to guardian_case_path(@guardian, @case)
    else
      render 'new'
    end
  end

  def show
    @guardian = Guardian.find(params[:guardian_id])
    @case = Case.find(params[:id])
  end

  private

  def case_params
    params.require(:case).permit(:guardian_id, :therapist_id, :teacher_id, :kid_id)
  end
end

app/controllers/guardians_controller.rb
class GuardiansController < ApplicationController
  def show
    @guardian = Guardian.find(params[:id])
  end

  def edit
    @guardian = Guardian.find(params[:id])
  end

  def update
    @guardian = Guardian.find(params[:id])

    if @guardian.update(guardian_params)
      redirect_to guardian_path(@guardian)
    else
      render 'edit'
    end
  end

  private

  def guardian_params
    params.require(:guardian).permit(:first_name, :last_name, :email)
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
    @guardian = Guardian.find(params[:guardian_id])
    @kids = @guardian.kids
  end

  def show
    @kid = Kid.find(params[:id])
  end

  def new
    @guardian = Guardian.find(params[:guardian_id])
    @kid = @guardian.kids.new
  end

  def create
    @guardian = Guardian.find(params[:guardian_id])
    @kid = @guardian.kids.new(kid_params)

    if @kid.save
      redirect_to guardian_kid_path(@guardian, @kid)
    else
      render 'new'
    end
  end

  def edit
    @kid = Kid.find(params[:id])
    @guardian = @kid.guardian
  end

  def update
    @kid = Kid.find(params[:id])

    if @kid.update_attributes(kid_params)
      redirect_to guardian_kid_path(@kid)
    else
      render 'edit'
    end
  end

  private

  def kid_params
    params.require(:kid).permit(:first_name, :last_name, :birthdate, :has_diagnosis, :guardian_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])

    if user.is_guardian?
      @user = Guardian.find(params[:id])

      redirect_to guardian_path(@user)
    elsif user.is_therapist?
      @user = Therapist.find(params[:id])
    else
      @user = Teacher.find(params[:id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/guardians_kids_helper.rb
module GuardiansKidsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cases/_form.html.erb
<%= form_for [@guardian, @case] do |f| %>
  <p>
    <%= f.label :therapist_id %>
    <%= f.number_field :therapist_id %>
  </p>
  <p>
    <%= f.label :teacher_id %>
    <%= f.number_field :teacher_id %>
  </p>
  <p>
    <%= f.label :kid_id %>
    <%= f.number_field :kid_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cases/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Guardian's Cases</title>
  </head>
  <body>
    <h1>All Guardian's Cases</h1>
    <h2><% @cases.each do |c| %></h2>
    <h3><%= link_to c.kid.first_name, guardian_case_path(@guardian, c) %></h3>
    <% end %>
  </body>
</html>

app/views/cases/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Case</title>
  </head>
  <body>
    <h1>New Case</h1>
      <%= render 'form' %>
  </body>
</html>

app/views/cases/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Case Show Page</title>
  </head>
  <body>
    <h1>Case Show Page</h1>
      <h3>Guardian: <%= @case.guardian.first_name + " " + @case.guardian.last_name %></h3>
      <h3>Kid: <%= @case.kid.first_name + " " + @case.kid.last_name %></h3>
      <% if @case.therapist %>
        <h3>Therapist: <%= @case.therapist.first_name + " " + @case.therapist.last_name %></h3>
      <% end %>
      <% if @case.teacher %>
        <h3>Teacher: <%= @case.teacher.first_name + " " + @case.teacher.last_name %></h3>
      <% end %>
      <%= link_to "Daily Reports", guardian_case_daily_reports_path(@guardian, @case) %>
      <!-- <% if @case.daily_reports %>
        <% @case.daily_reports.each do |report| %>
          <p>
            <%= report.body %>
            <%= report.guardian.first_name %>
            <%= report.created_at %>
          </p>
        <% end %>
      <% end %> -->
  </body>
</html>

app/views/kids/_form.html.erb
<%= form_for [@guardian, @kid] do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :birthdate %>
    <%= f.text_field :birthdate %>
  </p>
  <p>
    <%= f.label :has_diagnosis %>
    <%= f.select :has_diagnosis, [true, false] %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/kids/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Kid Profile</title>
  </head>
  <body>
    <h1>Edit Kid Profile</h1>
      <%= render 'form' %>
  </body>
</html>

app/views/kids/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= @guardian.first_name + "'s' kids" %></title>
  </head>
  <body>
    <% @kids.each do |kid| %>
      <ul>
        <h3><%= link_to kid.first_name, guardian_kid_path(@guardian, kid) %></h3>
      </ul>
    <% end %>
  </body>
</html>

app/views/kids/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Child</title>
  </head>
  <body>
    <h1>Add a Child</h1>
      <%= render 'form' %>
  </body>
</html>

app/views/kids/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= @kid.first_name + " " + @kid.last_name%></title>
  </head>
  <body>
    <h1><%= @kid.first_name + " " + @kid.last_name%></h1>
    <h3>Birthdate: <%= @kid.birthdate %></h3>
    <h3>Has Diagnosis: <%= @kid.has_diagnosis %></h3>

    <%= link_to "Edit", edit_guardian_kid_path(@kid) %>
  </body>
</html>